language: node_js
dist: xenial

node_js:
  - 8
  - 12
  - 14
  - node

os:
  - linux

stages:
  - lint
  - test_windows
  - test
  - codecov

jobs:
  include:
    - stage: lint
      name: ESlint
      node_js: node
      os: linux
      script: npm run lint
    - stage: test_windows
      name: Oldest supported version on Windows
      node_js: 8
      os: windows
    - stage: codecov
      name: Coveralls
      node_js: node
      os: linux
      script: npm run test && npm run coveralls

script: npm run test

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/de552aa9082bfddb180d
    on_cancel: never